routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => true,
    'verify' => false,
]);

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::prefix('dashboard')->name('dashboard.')->middleware(['middleware' => 'auth'])->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('settings', 'DashboardController@settings')->name('settings');
    Route::post("settings", "DashboardController@update_settings")->name('update_settings');
});
Route::prefix('api')->name('api.')->middleware('auth')->group(function () {
    Route::get('members', 'MemberController@api')->name('members');
    Route::get('member/{member}/loans', 'MemberController@loans')->name('loans');
});

Route::prefix('members')->name('member.')->middleware(['auth'])->group(function () {
    Route::get('/', 'MemberController@index')->name('index');
    Route::get('deactivated', 'MemberController@deactivated_members')->name('deactivated_members');
    Route::get('view/{member}', 'MemberController@show')->name('view');
    Route::get('update/{member}', 'MemberController@update')->name('update');
    Route::get('register', 'MemberController@create')->name('register');
    Route::post('store', 'MemberController@store')->name('store');
    Route::get('deactivate/{member}', 'MemberController@deactivationForm')->name('deactivation_form');
    Route::post('deactivate/{member}', 'MemberController@deactivate')->name('deactivate');
    Route::get('reactivate/{member}', 'MemberController@reactivate')->name('reactivate');
    Route::post('delete/{member}', 'MemberController@destroy')->name('delete');
});
Route::prefix('collateral')->middleware(['auth'])->name('collateral.')->group(function () {
    Route::get('all', 'CollateralController@index')->name('all');
    Route::get('view', 'CollateralController@show')->name('show');
    Route::get('add', 'CollateralController@create')->name('add');
    Route::post('add', 'CollateralController@store')->name('store');
    Route::get('{collateral}/edit', 'CollateralController@edit')->name('edit');
    Route::post('{collateral}/edit', 'CollateralController@update')->name('update');
    Route::delete('{collateral}/delete', 'CollateralController@destroy')->name('destroy');
});


Route::prefix('staff')->name('staff.')->middleware(['middleware' => 'auth'])->group(function () {
    Route::get('/', 'StaffController@index')->name('index');
    Route::get('create', 'StaffController@create')->name('create');
    Route::get('view/{staff}', 'StaffController@show')->name('show');
    Route::post('store', 'StaffController@store')->name('store');
    Route::get('update/{staff}', 'StaffController@update')->name('update');
    Route::patch('update/{staff}', 'StaffController@store')->name('patch');
    Route::delete('destroy/{staff}', 'StaffController@destroy')->name('destroy');
});

Route::prefix('loan')->name('loan.')->middleware(['middleware' => 'auth'])->group(function () {
    Route::get('/', 'LoanController@index')->name('index');

    Route::get('unappoved', 'LoanController@unapproved')->name('unapproved');
    Route::get('approve/{loan}', 'LoanController@approve')->name('approve');

    Route::get('release', 'LoanController@release')->name('release');
    Route::post('release', 'LoanController@release_loan')->name('release_loan');

    /*show loan form - with prefilled loan type*/
    Route::get('register/{loan_type}', 'LoanController@create')->name('register');
    Route::post('register/{loan_type}', 'LoanController@store')->name('store');

    /* edit loan form - with prefilled loan type*/
    Route::get('update/{loan_type}/{loan}', 'LoanController@edit')->name('update');
    Route::post('update/{loan_type}/{loan}}', 'LoanController@store')->name('loan_update');

    /*view whole loan information */
    Route::get('view/{loan_type}/{loan}', 'LoanController@view')->name('view');
    /*delete*/
    Route::get('destroy/{loan_type}/{loan}', 'LoanController@destroy')->name('delete');
    Route::get('print/{loan_type}/{loan}', 'LoanController@print')->name('print');

    Route::get('suspend/{loan}', 'LoanController@loanSuspensionForm')->name('loan_suspension_form');
    Route::post('suspend/{loan}', 'LoanController@suspend')->name('suspend');
    Route::post('delete/{loan}', 'LoanController@destroy')->name('delete');

});
Route::prefix('loan-payment')->name('loan_payment.')->middleware(['middleware' => 'auth'])->group(function () {
    Route::get('/', 'LoanPaymentController@index')->name('index');
    Route::get('show/{payment}', 'LoanPaymentController@show')->name('show');
    Route::post('delete', 'LoanPaymentController@destroy')->name('destroy');
    Route::get('print/{payment}', 'LoanPaymentController@print')->name('print');

    Route::get('create', 'LoanPaymentController@create')->name('create');
    Route::get('create/{loan}', 'LoanPaymentController@create')->name('make_loan_payment');
    Route::post('create', 'LoanPaymentController@store')->name('store');
    Route::get('today', 'LoanPaymentController@today')->name('today');
    Route::get('week', 'LoanPaymentController@week')->name('week');
    Route::get('month', 'LoanPaymentController@month')->name('month');
    Route::get('year', 'LoanPaymentController@year')->name('year');
});

Route::prefix('dashboard')->name('dashboard.')->middleware(['middleware' => 'auth'])->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('settings', 'DashboardController@settings')->name('settings');
});

Route::group(['middleware' => 'auth'], function () {
    /*Delete this soon*/
    Route::get('table-list', function () {
        return view('pages.table_list');
    })->name('table');

    Route::get('typography', function () {
        return view('pages.typography');
    })->name('typography');

    Route::get('icons', function () {
        return view('pages.icons');
    })->name('icons');

    Route::get('map', function () {
        return view('pages.map');
    })->name('map');

    Route::get('notifications', function () {
        return view('pages.notifications');
    })->name('notifications');

    Route::get('rtl-support', function () {
        return view('pages.language');
    })->name('language');

    Route::get('upgrade', function () {
        return view('pages.upgrade');
    })->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/LoanPayment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class LoanPayment
 * @package App
 */
class LoanPayment extends Model
{
    protected $dates = ['payment_date','due_date'];
    protected $guarded = [];

    public function loan()
    {
        return $this->belongsTo(Loan::class);
    }

    public function received_by_staff()
    {
        return Staff::where([
            'id'=>$this->received_by
        ])->firstOrFail();
    }


}

app/Http/Controllers/LoanPaymentController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Loan;
use App\LoanPayment;
use App\Member;
use App\Staff;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

class LoanPaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $loan_payments = LoanPayment::orderBy('created_at', 'DESC')->get();
        if ($request->has('name')) {
            $loan_payments = LoanPayment::orderBy('loans.id', 'DESC')
                ->join('loans', 'loans.id', 'loan_payments.loan_id')
                ->join('members', 'members.id', '=', 'loans.member_id')
                ->orWhere('members.title', 'like', '%' . $request->get('name') . '%')
                ->orWhere('members.first_name', 'like', '%' . $request->get('name') . '%')
                ->orWhere('members.middle_name', 'like', '%' . $request->get('name') . '%')
                ->orWhere('members.last_name', 'like', '%' . $request->get('name') . '%')
                ->paginate(20);
        }
        return view('loan_payment.index')->with([
            'loan_payments' => $loan_payments,
            'request' => $request
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /* find member with unpaid loan */
        $member_with_loan = DB::table('members')
            ->join('loans', 'members.id', '=', 'loans.member_id')
            ->where('loans.balance', '>', 0)
            ->get();

        $staffs = Staff::all();

        return view('loan_payment.create')->with([
            'member_with_loan' => $member_with_loan,
            'staffs' => $staffs
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validatedData = $request->validate([
            'id' => '',
            'loan_id' => 'required',
            'due_date' => 'required',
            'payment_date' => 'required',
            'amount' => 'required',
            'received_by' => 'required'
        ]);

        if (isset($validatedData['id'])) {
            LoanPayment::updateOrCreate(['id' => @$validatedData['id']], $validatedData);
        } else {
            $loanPayment = LoanPayment::create($validatedData);
            /* reduce loan balance */

            $loanPayment->loan->balance = $loanPayment->loan->balance - $loanPayment->amount;
            $loanPayment->loan->save();
        }
        return redirect(url()->previous())->with('success', 'Loan payment accepted!');

    }

    public function show(LoanPayment $payment)
    {

        return view('loan_payment.show')->with([
            'loan_payment' => $payment
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\LoanPayment $loanPayment
     * @return \Illuminate\Http\Response
     */
    public function edit(LoanPayment $loanPayment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\LoanPayment $loanPayment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, LoanPayment $loanPayment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\LoanPayment $loanPayment
     * @return \Illuminate\Http\Response
     */
    public function destroy(LoanPayment $loanPayment)
    {
        dd($loanPayment);

    }

    public function today()
    {
        echo __METHOD__;
    }

    public function week()
    {
        /* get dates of this week */
        /*loop */
        $result['monday'] = date("Y-m-d", strtotime("this week monday"));
        $result['tuesday'] = date("Y-m-d", strtotime("this week tuesday"));
        $result['wednesday'] = date("Y-m-d", strtotime("this week wednesday"));
        $result['thursday'] = date("Y-m-d", strtotime("this week thursday"));
        $result['friday'] = date("Y-m-d", strtotime("this week friday"));
        $result['saturday'] = date("Y-m-d", strtotime("this week saturday"));
        $result['sunday'] = date("Y-m-d", strtotime("this week sunday"));
        foreach ($result as $weekDayName => $currentWeekDay) {
            /* search and count*/
            $result[$weekDayName] = $this->getWeekPaymentCount($currentWeekDay);
        }
        return $result;
    }

    private function getWeekPaymentCount(string $payment_date)
    {
        $result = DB::table('loan_payments')
            ->select(DB::raw('SUM(amount) as total_payment'))
            ->where('payment_date', '=', $payment_date)
            ->get();
        return floatval($result[0]->total_payment);
    }

    public function month()
    {
        $report = [];
        /* get dates of this week */
        foreach (range(1, 12) as $currentMonthNum) {
            $result = DB::table('loan_payments')
                ->select(DB::raw('SUM(amount) as total_payment'), DB::raw("month(payment_date) as payment_month_date"), DB::raw("monthname(payment_date) as monthname"))
                ->groupBy(['payment_month_date', 'monthname'])
                ->having('payment_month_date', '=', $currentMonthNum)
                ->get();
            $report[$currentMonthNum] = $result[0] ?? ['total_payment' => 0, 'payment_month_date' => $currentMonthNum, 'monthname' => date("F", strtotime("1991-$currentMonthNum-30"))];
        }

        return $report;
    }

    public function print(LoanPayment $payment)
    {
//        $pdf = PDF::loadView('print.loan_payment', $payment);
//        return $pdf->stream();
        return view('print')->with([
            'payment'=>$payment
        ]);
    }

}

resources/views/loan_payment/_form.blade.php
<form method="post" action="{{ route('loan_payment.store') }}" autocomplete="off" class="form-horizontal row">
    @csrf
    @method('post')
    @if ($errors->any())
        <div class="col-12">
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error</strong>
                <br>
                @if ($errors->any())
                    {!! implode('', $errors->all('<div>:message</div>')) !!}
                @endif

            </div>
        </div>
    @endif
    <div class="col-5">
        <legend class="">Member</legend>
        <select class="form-control" id="member_id" name="member_id">
            <option value="" selected="selected">-- Member --</option>
            @foreach($member_with_loan as $current_member_with_loan_balance)
                <option
                    value="{{$current_member_with_loan_balance->member_id}}" {{ ($current_member_with_loan_balance->id ?? old('member_id')) == $current_member_with_loan_balance->id ? "selected='selected'":""  }}>
                    {{ sprintf("%s %s %s",$current_member_with_loan_balance->title , $current_member_with_loan_balance->first_name , $current_member_with_loan_balance->last_name) }}
                </option>
            @endforeach
        </select>
        <div id="member_loan_container" class="mt-5">
            <legend>Loan balance of selected member</legend>
            <select name="loan_id" id="loan_id" class="form-control">
                <option value="" selected="selected">-- List of loan --</option>
            </select>
            @if ($errors->has('loan_id'))
                <span id="name-error" class="error text-danger"
                      for="input-name">{{ $errors->first('loan_id') }}</span>
            @endif
        </div>
        <legend class="mt-5">Amount</legend>
        <div class="form-group {{ $errors->has('amount') ? ' has-danger' : '' }}">
            <input step="0.01" type="number" class="form-control" id="amount" name="amount"
                   value="{{ isset($loan_payment->amount) ?   $loan_payment->amount:old('amount')  }}">
            @if ($errors->has('amount'))
                <span id="name-error" class="error text-danger"
                      for="input-name">{{ $errors->first('amount') }}</span>
            @endif
        </div>
        <legend class="mt-5">Received by</legend>
        <select class="form-control" id="received_by" name="received_by">
            <option value="" selected="selected">-- Received by --</option>
            @foreach($staffs as $current_staff)
                <option
                    value="{{ $current_staff->id  }}" {{ ( $loan_payment->received_by ?? old('received_by') ) == $current_staff->id  ? "selected='selected'":""  }}>
                    {{ sprintf("%s %s %s",$current_staff->title , $current_staff->first_name , $current_staff->last_name) }}
                </option>
            @endforeach
        </select>
        @if ($errors->has('received_by'))
            <span id="name-error" class="error text-danger"
                  for="input-name">{{ $errors->first('received_by') }}</span>
        @endif
    </div>
    <div class="col-4 ml-3">
        <legend>Loan Information</legend>
        <label for="loan_maturity_date">Loan Date</label>
        <input type="text" class="form-control" id="loan_date" name="loan_date" readonly="readonly" value="">
        @if ($errors->has('loan_date'))
            <span id="name-error" class="error text-danger"
                  for="input-name">{{ $errors->first('loan_date') }}</span>
        @endif
        <label for="loan_maturity_date" class="mt-3">Maturity Date</label>
        <input type="text" class="form-control" id="loan_maturity_date" name="maturity_date" readonly="readonly"
               value="">
        @if ($errors->has('loan_maturity_date'))
            <span id="name-error" class="error text-danger"
                  for="input-name">{{ $errors->first('loan_maturity_date') }}</span>
        @endif
        <label for="payment_due_date" class="mt-3">Payment Due Date</label>
        <input type="hidden" class="form-control" id="payment_due_date" name="due_date" readonly="readonly" value="">
        <input type="text" class="form-control" id="payment_due_date_formatted" name="due_date_formatted"
               readonly="readonly" value="">
        @if ($errors->has('due_date'))
            <span id="name-error" class="error text-danger"
                  for="input-name">{{ $errors->first('due_date') }}</span>
        @endif
        <label for="next_payment_due_date" class="mt-3">Next Payment Due Date</label>
        <input type="hidden" class="form-control" id="next_payment_due_date" name="next_due_date" readonly="readonly"
               value="">
        <input type="text" class="form-control" id="next_payment_due_date_formatted" name="next_due_date_formatted"
               readonly="readonly" value="">
        @if ($errors->has('next_payment_due_date_formatted'))
            <span id="name-error" class="error text-danger"
                  for="input-name">{{ $errors->first('next_payment_due_date_formatted') }}</span>
        @endif

        <label for="next_payment_due_date" class="mt-3">Remaining Balance</label>
        <input type="text" class="form-control" id="remaining_balance" name="remaining_balance" readonly="readonly" >

        <input type="hidden" value="{{ \Carbon\Carbon::now()->format("Y-m-d") }}"  name="payment_date">
    </div>
    <div class="col-2">
        <legend>Terms</legend>
        <strong id="number_of_terms">##</strong> <br>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-block btn-primary">
            {{ __('Make payment') }}
        </button>
    </div>
</form>
@push('js')
    <script type="text/javascript">
        var loanPaymentForm = new LoanPaymentForm({
            'memberField': "member_id",
            'loan_member': 'loan_id',
            'amount_per_installment': 'amount',
            'loan_date': 'loan_date',
            'maturity_date_field': 'loan_maturity_date',
            'payment_due_date': 'payment_due_date',
            'payment_due_date_formatted': 'payment_due_date_formatted',
            'next_payment_due_date': 'next_payment_due_date',
            'next_payment_due_date_formatted': 'next_payment_due_date_formatted',
            'remaining_balance': 'remaining_balance',
            'number_of_terms':'number_of_terms'
        });
        jQuery("#member_id").change(function (event) {
            let member_id = jQuery(this).val();
            loanPaymentForm.loadMemberLoan(member_id)
        });
    </script>
@endpush

resources/views/loan_payment/create.blade.php
@extends('layouts.app', ['activePage' => 'loan_payment', 'titlePage' => __('Make loan payment')])
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if(session()->has('success'))
                        <div class="alert alert-info" role="alert">
                            {{ session()->get('success')  }}
                        </div>
                    @endif

                    <div class="card ">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">{{ __('Member Information') }}</h4>
                            <p class="card-category"></p>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-12">
                                    <a href="{{ route('loan_payment.index') }}"
                                       class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                                </div>
                            </div>
                            <br>
                            @include('loan_payment._form',compact('member_with_loan'))
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/loan_payment/index.blade.php
@extends('layouts.app', ['activePage' => 'loan_payment', 'titlePage' => __('Loan Payment')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">
                                {{ env('APP_NAME')  }} Loan Payment
                            </h4>
                            <p class="card-category">
                                Loan Payment History Record
                            </p>
                        </div>
                        <div class="card-body">
                            <div class="row mt-3">
                                <div class="col-12">
                                    <form action="{{url()->current()}}">
                                        @if($request->has('name'))
                                            Search result : {{$request->get('name')}}
                                        @endif
                                        <div class="input-group mb-3">
                                            <input autofocus type="text" class="form-control" placeholder="Search member (e.g John Doe)" aria-label="Search member (e.g John Doe)" aria-describedby="basic-addon2" name="name">
                                            <div class="input-group-append">
                                                <button class="btn btn-sm btn-outline-secondary" type="button">
                                                    <i class="fa fa-search" style="font-size: 13px"></i>
                                                    Search
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <a href="{{ route('loan_payment.create') }}"
                                       class="btn btn-sm btn-primary">{{ __('Make Payment') }}</a>
                                </div>
                            </div>

                            <div class="table-responsive">
                                <table class="table mt-3">
                                    <thead class=" text-primary">
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Contact #
                                    </th>
                                    <th>
                                        Payment
                                    </th>
                                    <th>
                                        Payment Date
                                    </th>
                                    <th class="text-center">
                                        Action
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($loan_payments as $current_loan_payment)
                                        <tr>
                                            <td>
                                                <a href="{{route('member.view',['member'=>$current_loan_payment->loan->member->id])}}">
                                                    {{$current_loan_payment->loan->member->getFullName()}}
                                                </a>
                                            </td>
                                            <td>
                                                {{$current_loan_payment->loan->member->mobile_number}}
                                            </td>
                                            <td class="text-info">
                                                {{
                                                    @peso($current_loan_payment->amount)
                                                }}
                                            </td>
                                            <td class="text-warning">
                                                {{ $current_loan_payment->payment_date->format("F d,Y") }}
                                            </td>
                                            <td class="td-actions text-center">
                                                <a href="{{route('loan_payment.show',['payment'=>$current_loan_payment->id])}}">
                                                    <i class="fa fa-eye"></i> View
                                                </a>
                                                <a href="{{route('loan_payment.print',['payment'=>$current_loan_payment->id])}}">
                                                    <i class="fa fa-print"></i> Print
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/loan_payment/show.blade.php
@extends('layouts.app', ['activePage' => 'loan', 'titlePage' => __('All Loans')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">
                                {{ env('APP_NAME')  }} Loan Payment
                            </h4>
                            <p class="card-category">
                            </p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <a href="{{ route('loan_payment.index') }}"
                                       class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 " >
                                    <legend class="text-center mt-5">
                                        Payment Transaction Information
                                    </legend>
                                    <table class="table table-bordered table-hover mt-3" style="margin:  0px auto; width: 80%">
                                        <tbody>
                                        <tr>
                                            <td><strong><label for="loan_rate_id" class="bmd-label-static">Loan
                                                        </label></strong></td>
                                            <td>
                                                <a href="{{route('loan.view',['loan_type'=>strtolower($loan_payment->loan->loan_type),'loan'=>$loan_payment->loan->id])}}">
                                                    {{ $loan_payment->loan->loan_type }} | Date Loaned : {{ $loan_payment->loan->date_loaned->format("F d,Y")  }}
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><strong><label for="date_loaned" class="bmd-label-static">Payment Date</label></strong></td>
                                            <td>{{$loan_payment->payment_date->format("F d,y")}}</td>
                                        </tr>
                                        <tr>
                                            <td><strong><label for="loan_type" class="bmd-label-static">Due Date</label></strong></td>
                                            <td>{{$loan_payment->due_date->format("F d,Y")}}</td>
                                        </tr>
                                        <tr>
                                            <td><strong><label for="amount_loaned" class="bmd-label-static">Amount</label></strong></td>
                                            <td>{{ @peso($loan_payment->amount) }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong><label for="maturity_date" class="bmd-label-static"> Received By </label></strong></td>
                                            <td>
                                                {{$loan_payment->received_by_staff()->fullName()}}
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection